// Generated by 'dotnet run -p build/MakeOpenGLInterop test\WindowSystem.ManualTest\glinterop.xml'
//

using GLbitfield = System.UInt32;
using GLboolean = System.Byte;
using GLenum = System.UInt32;
using GLint = System.Int32;

namespace NStuff.WindowSystem.ManualTest
{
    internal enum AttributeElementType : GLenum
    {
        Byte = 0x1400,
        UnsignedByte = 0x1401,
        Short = 0x1402,
        UnsignedShort = 0x1403,
        Int = 0x1404,
        UnsignedInt = 0x1405,
        HalfFloat = 0x140B,
        Float = 0x1406,
        Fixed = 0x140C,
        Int2101010Rev = 0x8D9F,
        UnsignedInt2101010Rev = 0x8368,
    }

    internal enum BlendingFactor : GLenum
    {
        ConstantAlpha = 0x8003,
        ConstantColor = 0x8001,
        OneMinusConstantAlpha = 0x8004,
        OneMinusConstantColor = 0x8002,
        DstAlpha = 0x0304,
        DstColor = 0x0306,
        One = 1,
        OneMinusDstAlpha = 0x0305,
        OneMinusDstColor = 0x0307,
        OneMinusSrcAlpha = 0x0303,
        OneMinusSrcColor = 0x0301,
        OneMinusSrc1Alpha = 0x88FB,
        OneMinusSrc1Color = 0x88FA,
        SrcAlpha = 0x0302,
        SrcColor = 0x0300,
        Src1Alpha = 0x8589,
        Src1Color = 0x88F9,
        SrcAlphaSaturate = 0x0308,
        Zero = 0,
    }

    internal enum Boolean : GLboolean
    {
        False = 0,
        True = 1,
    }

    internal enum Buffers : GLbitfield
    {
        Color = 0x00004000,
        Depth = 0x00000100,
        Stencil = 0x00000400,
    }

    internal enum BufferTarget : GLenum
    {
        Array = 0x8892,
        AtomicCounter = 0x92C0,
        CopyRead = 0x8F36,
        CopyWrite = 0x8F37,
        DispatchIndirect = 0x90EE,
        DrawIndirect = 0x8F3F,
        ElementArray = 0x8893,
        PixelPack = 0x88EB,
        PixelUnpack = 0x88EC,
        ShaderStorage = 0x90D2,
        TransformFeedback = 0x8C8E,
        Uniform = 0x8A11,
    }

    internal enum BufferUsage : GLenum
    {
        DynamicCopy = 0x88EA,
        DynamicDraw = 0x88E8,
        DynamicRead = 0x88E9,
        StaticCopy = 0x88E6,
        StaticDraw = 0x88E4,
        StaticRead = 0x88E5,
        StreamCopy = 0x88E2,
        StreamDraw = 0x88E0,
        StreamRead = 0x88E1,
    }

    internal enum Capability : GLenum
    {
        Blend = 0x0BE2,
        CullFace = 0x0B44,
        DepthTest = 0x0B71,
        Dither = 0x0BD0,
        PolygonOffsetFill = 0x8037,
        PrimitiveRestartFixedIndex = 0x8D69,
        RasterizerDiscard = 0x8C89,
        SampleAlphaToCoverage = 0x809E,
        SampleCoverage = 0x80A0,
        SampleMask = 0x8E51,
        ScissorTest = 0x0C11,
        StencilTest = 0x0B90,
    }

    internal enum DrawIndexType : GLenum
    {
        UnsignedByte = 0x1401,
        UnsignedShort = 0x1403,
        UnsignedInt = 0x1405,
    }

    internal enum DrawMode : GLenum
    {
        Points = 0x0000,
        LineStrip = 0x0003,
        LineLoop = 0x0002,
        Lines = 0x0001,
        TriangleStrip = 0x0005,
        TriangleFan = 0x0006,
        Triangles = 0x0004,
    }

    internal enum PixelFormat : GLenum
    {
        Red = 0x1903,
        RedInteger = 0x8D94,
        Rg = 0x8227,
        RgInteger = 0x8228,
        Rgb = 0x1907,
        RgbInteger = 0x8D98,
        Rgba = 0x1908,
        RgbaInteger = 0x8D99,
        DepthComponent = 0x1902,
        DepthStencil = 0x84F9,
    }

    internal enum PixelStoreParameter : GLenum
    {
        PackRowLength = 0x0D02,
        PackImageHeight = 0x806C,
        PackSkipPixels = 0x0D04,
        PackSkipRows = 0x0D03,
        PackSkipImages = 0x806B,
        PackAlignment = 0x0D05,
        UnpackRowLength = 0x0CF2,
        UnpackImageHeight = 0x806E,
        UnpackSkipPixels = 0x0CF4,
        UnpackSkipRows = 0x0CF3,
        UnpackSkipImages = 0x806D,
        UnpackAlignment = 0x0CF5,
    }

    internal enum PixelType : GLenum
    {
        Byte = 0x1400,
        Float = 0x1406,
        HalfFloat = 0x140B,
        Int = 0x1404,
        Short = 0x1402,
        UnsignedByte = 0x1401,
        UnsignedInt = 0x1405,
        UnsignedShort = 0x1403,
        UnsignedInt10f11f11fRev = 0x8C3B,
        UnsignedInt5999Rev = 0x8C3E,
        UnsignedShort5551 = 0x8034,
        UnsignedShort565 = 0x8363,
        UnsignedShort4444 = 0x8033,
        UnsignedInt2101010Rev = 0x8368,
        UnsignedInt248 = 0x84FA,
        Float32UnsignedInt248Rev = 0x8DAD,
    }

    internal enum ProgramParameter : GLenum
    {
        ActiveAtomicCounterBuffers = 0x92D9,
        ActiveAttributes = 0x8B89,
        ActiveAttributeMaxLength = 0x8B8A,
        ActiveUniforms = 0x8B86,
        ActiveUniformBlocks = 0x8A36,
        ActiveUniformBlockMaxNameLength = 0x8A35,
        ActiveUniformMaxLength = 0x8B87,
        AttachedShaders = 0x8B85,
        ComputeWorkGroupSize = 0x8267,
        DeleteStatus = 0x8B80,
        InfoLogLength = 0x8B84,
        LinkStatus = 0x8B82,
        ProgramBinaryRetrievableHint = 0x8257,
        ProgramSeparable = 0x8258,
        TransformFeedbackBufferMode = 0x8C7F,
        TransformFeedbackVaryings = 0x8C83,
        TransformFeedbackVaryingMaxLength = 0x8C76,
        ValidateStatus = 0x8B83,
    }

    internal enum ShaderParameter : GLenum
    {
        ShaderType = 0x8B4F,
        DeleteStatus = 0x8B80,
        CompileStatus = 0x8B81,
        InfoLogLength = 0x8B84,
        ShaderSourceLength = 0x8B88,
    }

    internal enum ShaderType : GLenum
    {
        Fragment = 0x8B30,
        Vertex = 0x8B31,
    }

    internal enum StringParameter : GLenum
    {
        Extensions = 0x1F03,
        Vendor = 0x1F00,
        Renderer = 0x1F01,
        Version = 0x1F02,
        ShadingLanguageVersion = 0x8B8C,
    }

    internal enum TextureParameteri : GLenum
    {
        DepthStencilTextureMode = 0x90EA,
        TextureBaseLevel = 0x813C,
        TextureMaxLevel = 0x813D,
        TextureCompareFunc = 0x884D,
        TextureCompareMode = 0x884C,
        TextureMinFilter = 0x2801,
        TextureMagFilter = 0x2800,
        TextureSwizzleR = 0x8E42,
        TextureSwizzleG = 0x8E43,
        TextureSwizzleB = 0x8E44,
        TextureSwizzleA = 0x8E45,
        TextureWrapS = 0x2802,
        TextureWrapT = 0x2803,
        TextureWrapR = 0x8072,
    }

    internal enum TextureParameterValue : GLint
    {
        DepthComponent = 0x1902,
        StencilIndex = 0x1901,
        CompareRefToTexture = 0x884E,
        Lequal = 0x0203,
        Gequal = 0x0206,
        Less = 0x0201,
        Greater = 0x0204,
        Equal = 0x0202,
        Notequal = 0x0205,
        Always = 0x0207,
        Never = 0x0200,
        None = 0,
        Nearest = 0x2600,
        Linear = 0x2601,
        NearestMipmapNearest = 0x2700,
        LinearMipmapNearest = 0x2701,
        NearestMipmapLinear = 0x2702,
        LinearMipmapLinear = 0x2703,
        Red = 0x1903,
        Green = 0x1904,
        Blue = 0x1905,
        Alpha = 0x1906,
        Zero = 0,
        One = 1,
        ClampToEdge = 0x812F,
        MirroredRepeat = 0x8370,
        Repeat = 0x2901,
    }

    internal enum TexturePixelFormat : GLint
    {
        R8 = 0x8229,
        R8Snorm = 0x8F94,
        R16f = 0x822D,
        R32f = 0x822E,
        R8ui = 0x8232,
        R8i = 0x8231,
        R16ui = 0x8234,
        R16i = 0x8233,
        R32ui = 0x8236,
        R32i = 0x8235,
        Rg8 = 0x822B,
        Rg8Snorm = 0x8F95,
        Rg16f = 0x822F,
        Rg32f = 0x8230,
        Rg8ui = 0x8238,
        Rg8i = 0x8237,
        Rg16ui = 0x823A,
        Rg16i = 0x8239,
        Rg32ui = 0x823C,
        Rg32i = 0x823B,
        Rgb8 = 0x8051,
        Srgb8 = 0x8C41,
        Rgb565 = 0x8D62,
        Rgb8Snorm = 0x8F96,
        R11fG11fB10f = 0x8C3A,
        Rgb9E5 = 0x8C3D,
        Rgb16f = 0x881B,
        Rgb32f = 0x8815,
        Rgb8ui = 0x8D7D,
        Rgb8i = 0x8D8F,
        Rgb16ui = 0x8D77,
        Rgb16i = 0x8D89,
        Rgb32ui = 0x8D71,
        Rgb32i = 0x8D83,
        Rgba8 = 0x8058,
        Srgb8Alpha8 = 0x8C43,
        Rgba8Snorm = 0x8F97,
        Rgb5A1 = 0x8057,
        Rgba4 = 0x8056,
        Rgb10A2 = 0x8059,
        Rgba16f = 0x881A,
        Rgba32f = 0x8814,
        Rgba8ui = 0x8D7C,
        Rgba8i = 0x8D8E,
        Rgb10A2ui = 0x906F,
        Rgba16ui = 0x8D76,
        Rgba16i = 0x8D88,
        Rgba32i = 0x8D82,
        Rgba32ui = 0x8D70,
        DepthComponent16 = 0x81A5,
        DepthComponent24 = 0x81A6,
        DepthComponent32f = 0x8CAC,
        Depth24Stencil8 = 0x88F0,
        Depth32fStencil8 = 0x8CAD,
    }

    internal enum TextureTarget : GLenum
    {
        Texture2d = 0x0DE1,
        Texture2dArray = 0x8C1A,
        Texture2dMultisample = 0x9100,
        Texture3d = 0x806F,
        TextureCubeMap = 0x8513,
    }

    internal enum TextureTarget2D : GLenum
    {
        Texture2d = 0x0DE1,
        TextureCubeMapPositiveX = 0x8515,
        TextureCubeMapPositiveY = 0x8517,
        TextureCubeMapPositiveZ = 0x8519,
        TextureCubeMapNegativeX = 0x8516,
        TextureCubeMapNegativeY = 0x8518,
        TextureCubeMapNegativeZ = 0x851A,
    }

    internal enum TextureUnit : GLenum
    {
        Texture0 = 0x84C0,
        Texture1 = 0x84C1,
        Texture2 = 0x84C2,
        Texture3 = 0x84C3,
        Texture4 = 0x84C4,
        Texture5 = 0x84C5,
        Texture6 = 0x84C6,
        Texture7 = 0x84C7,
        Texture8 = 0x84C8,
        Texture9 = 0x84C9,
        Texture10 = 0x84CA,
        Texture11 = 0x84CB,
        Texture12 = 0x84CC,
        Texture13 = 0x84CD,
        Texture14 = 0x84CE,
        Texture15 = 0x84CF,
        Texture16 = 0x84D0,
        Texture17 = 0x84D1,
        Texture18 = 0x84D2,
        Texture19 = 0x84D3,
        Texture20 = 0x84D4,
        Texture21 = 0x84D5,
        Texture22 = 0x84D6,
        Texture23 = 0x84D7,
        Texture24 = 0x84D8,
        Texture25 = 0x84D9,
        Texture26 = 0x84DA,
        Texture27 = 0x84DB,
        Texture28 = 0x84DC,
        Texture29 = 0x84DD,
        Texture30 = 0x84DE,
        Texture31 = 0x84DF,
    }

}
