namespace NStuff.Tessellation
{
    /// <summary>
    /// Lists the kind of output produced by the tessellator.
    /// </summary>
    public enum OutputKind
    {
        /// <summary>
        /// Any graphics primitive can be generated by the tessellator, for instance a combination of triangles,
        /// triangle strips, or triangle fans.
        /// </summary>
        AnyPrimitives,

        /// <summary>
        /// A line loop representing the boundary of the polygon is expected.
        /// </summary>
        BoundaryOnly,

        /// <summary>
        /// A set of triangles is expected from the tessellator.
        /// </summary>
        TrianglesOnly,

        /// <summary>
        /// A line loop describing the boundary of the polygon is expected, using the enumerator API.
        /// </summary>
        BoundaryEnumerator,

        /// <summary>
        /// A set of triangles is expected from the tessellator, using the enumerator API.
        /// </summary>
        TriangleEnumerator,
    }
}
